# Generated by Django 4.0.4 on 2022-05-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '谷歌邮箱',
                'verbose_name_plural': '谷歌邮箱',
            },
        ),
        migrations.CreateModel(
            name='hotmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '微软邮箱',
                'verbose_name_plural': '微软邮箱',
            },
        ),
        migrations.CreateModel(
            name='net163',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '网易邮箱',
                'verbose_name_plural': '网易邮箱',
            },
        ),
        migrations.CreateModel(
            name='OutlookMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '微软邮箱',
                'verbose_name_plural': '微软邮箱',
            },
        ),
    ]
