# Generated by Django 4.0.4 on 2022-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlookmail',
            options={},
        ),
        migrations.AddField(
            model_name='outlookmail',
            name='flag',
            field=models.IntegerField(default=0, max_length=1, verbose_name='是否使用'),
        ),
    ]
