# Generated by Django 4.0.4 on 2022-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0002_alter_outlookmail_options_outlookmail_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmail',
            name='app',
            field=models.CharField(default='', max_length=255, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='gmail',
            name='flag',
            field=models.IntegerField(default=0, max_length=1, verbose_name='是否使用'),
        ),
        migrations.AddField(
            model_name='hotmail',
            name='app',
            field=models.CharField(default='', max_length=255, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='hotmail',
            name='flag',
            field=models.IntegerField(default=0, max_length=1, verbose_name='是否使用'),
        ),
        migrations.AddField(
            model_name='net163',
            name='app',
            field=models.CharField(default='', max_length=255, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='net163',
            name='flag',
            field=models.IntegerField(default=0, max_length=1, verbose_name='是否使用'),
        ),
        migrations.AddField(
            model_name='outlookmail',
            name='app',
            field=models.CharField(default='', max_length=255, verbose_name='来源'),
        ),
    ]
