# Generated by Django 4.0.4 on 2022-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0003_gmail_app_gmail_flag_hotmail_app_hotmail_flag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlookmail',
            options={'verbose_name': '微软邮箱', 'verbose_name_plural': '微软邮箱'},
        ),
        migrations.AddField(
            model_name='gmail',
            name='created',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AddField(
            model_name='gmail',
            name='last_get',
            field=models.IntegerField(default=0, verbose_name='上次获取的时间戳'),
        ),
        migrations.AddField(
            model_name='gmail',
            name='status',
            field=models.IntegerField(default=0, verbose_name='注册 ins 状态'),
        ),
        migrations.AddField(
            model_name='hotmail',
            name='created',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AddField(
            model_name='hotmail',
            name='last_get',
            field=models.IntegerField(default=0, verbose_name='上次获取的时间戳'),
        ),
        migrations.AddField(
            model_name='hotmail',
            name='status',
            field=models.IntegerField(default=0, verbose_name='注册 ins 状态'),
        ),
        migrations.AddField(
            model_name='net163',
            name='created',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AddField(
            model_name='net163',
            name='last_get',
            field=models.IntegerField(default=0, verbose_name='上次获取的时间戳'),
        ),
        migrations.AddField(
            model_name='net163',
            name='status',
            field=models.IntegerField(default=0, verbose_name='注册 ins 状态'),
        ),
        migrations.AddField(
            model_name='outlookmail',
            name='created',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AddField(
            model_name='outlookmail',
            name='last_get',
            field=models.IntegerField(default=0, verbose_name='上次获取的时间戳'),
        ),
        migrations.AddField(
            model_name='outlookmail',
            name='status',
            field=models.IntegerField(default=0, verbose_name='注册 ins 状态'),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='是否使用'),
        ),
        migrations.AlterField(
            model_name='hotmail',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='是否使用'),
        ),
        migrations.AlterField(
            model_name='net163',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='是否使用'),
        ),
        migrations.AlterField(
            model_name='outlookmail',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='是否使用'),
        ),
    ]
