# Generated by Django 4.0.4 on 2022-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0004_alter_outlookmail_options_gmail_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='created',
            field=models.IntegerField(default=0, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AlterField(
            model_name='hotmail',
            name='created',
            field=models.IntegerField(default=0, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AlterField(
            model_name='net163',
            name='created',
            field=models.IntegerField(default=0, verbose_name='邮箱数据入库时间'),
        ),
        migrations.AlterField(
            model_name='outlookmail',
            name='created',
            field=models.IntegerField(default=0, verbose_name='邮箱数据入库时间'),
        ),
    ]
